version: '3'
services:
  app:
    image: laravelphp/php-fpm:8.2
    container_name: mycows_app
    volumes:
      - ./:/var/www/html
    environment:
      WWWGROUP: '1000'
      WWWUSER: '1000'
    networks:
      - sail
    ports:
      - "80:80"
  postgres:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mycows_rfi
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - sail
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - sail
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  db-data:
    driver: local
